### ISSUE TITLE
Error with prim path on non-windows?

### ISSUE THREAD

**Issue by bsavery** [philsawicki/moana-to-usd#1]
https://github.com/philsawicki/moana-to-usd/blob/9ecaedcc965b28f1631d0f7b7d740e1e33aef4ce/moana2usd/converters/asset_converter.py#L92

I get this stack trace here:  
`Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/bsavery/Documents/GitHub/moana-to-usd/moana2usd/__main__.py", line 60, in <module>
    moanaIslandConverter.convert()
  File "moana2usd/converters/scene_converter.py", line 70, in convert
    self._assetConverter.convert()
  File "moana2usd/converters/asset_converter.py", line 38, in convert
    self._createAssets()
  File "moana2usd/converters/asset_converter.py", line 647, in _createAssets
    self._translateOBJFileIntoUSD(assetOBJPath)
  File "moana2usd/converters/asset_converter.py", line 312, in _translateOBJFileIntoUSD
    self._convertOBJToUSD(assetOBJPath, objStream)
  File "moana2usd/converters/asset_converter.py", line 92, in _convertOBJToUSD
    elementName = os.path.relpath(assetOBJPath, self.SourceDirectoryPath).split('\\')[1]`

I _THINK_ you are trying to get the obj file name and use that for a prim path in USD?  Not sure about the \\ so assuming that is to deal with windows file paths maybe?  Anyway so for this example the error comes up with relpath of 'obj/isBayCedarA1/isBayCedarA1.obj' that of course cannot be split by \\.  The path then for the usd prim wants to be /obj/isBayCedarA1/isBayCedarA1.obj ?

**Comment by bsavery** [comment]
`elementName = os.path.relpath(assetOBJPath, self.SourceDirectoryPath)`
 I changed it to this
Furthermore... I think you can't create a prim with the .obj there which is another error.  So maybe:
`elementName = os.path.spiltext(os.path.relpath(assetOBJPath, self.SourceDirectoryPath))[0]`

**Comment by bsavery** [comment]
ah ok.  I think I figured out the intention, you want to maybe do:
`os.path.relpath(assetOBJPath, self.SourceDirectoryPath).split(os.sep)[1]`

**Comment by kaedehao** [comment]
> ah ok. I think I figured out the intention, you want to maybe do:
> `os.path.relpath(assetOBJPath, self.SourceDirectoryPath).split(os.sep)[1]`

This is very helpful， thanks!

Btw, did you manage to convert the whole scene? I somehow get stuck at 65%, not sure if I get everything right

**Comment by bsavery** [comment]
Same here.  I'm not sure which file, but I think it gets stuck in some loop parsing one of the objs
